# -*- coding: utf-8 -*-
"""Lab1_19521970

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yrjmVO-XomRho49V3feXcXiK1bAY4lwN
"""

7**4

"""What is 7 to the power of 4?

Split this string:
"""

s='Hi there Sam'

"""into list."""

s.split(" ")

"""given the variables:
Use format() to print the following string. 
"""

planet='Earth'
diameter=12742

"The diameter of {} is {} kilometers.".format(planet,diameter)

"""Given this nested list, use indexing to grap the word "hello"
"""

lst=[1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

lst[3][1][2][0]

"""Given this nested dictionary grab the word "Hello". Be repared, this will be annoying/ tricky"""

d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d['k1'][3]['tricky'][3]['target'][3]

"""What is the main different between a tuple and a list? 
Create a function that graps the email website domain from a string in the form:
      user@domain.com
So for exmaple, passing "user@domain.com" would return domain.com

"""

def domainGet(email):
  return email.split("@")[1]

domainGet("user@domain.com")

"""Create a basis function taht returns to if the word "dog" is contained in the input string.Don't worry about edge cases like a punctuation being attached to the word dog, but do account for capitalization """

def findDog(s):
  return 'dog' in s

findDog('Is there a dog here?')

"""Create a function that counts the number of time the word "dog" occurs in a string. Again ignore edge cases """

def countDog(s):
  return s.count('dog')

countDog('This dog runs faster thann the other dog dule!')

"""Use lambda expressions and the filter()function to filter out a word from a list that don't start with the letter 's'. For example: """

seq =['soup','dog','salad','cat','great']

list (filter(lambda item: item[0]=='s',seq))

"""# Final Problem 

You are littel too fast, and a police officer stop you. Write a function to return one of three possible resufts: "No ticket", "small ticket", "big ticket". If your speed  is 60 or less, the results is " No ticket". If speed is between 61 and 80 inclusive, the results is "Big ticket". Unless it is your birthday (encoded as a boolean value in the parametters of the function)-- On your birthday, your speed can be higher in all cases. 
"""

def caught_speeding(speed,is_birthday):
  if(is_birthday):
    speed=speed-5
  print(speed)
  if(speed<61):
    return 'No Ticket'
  elif(speed<81):
    return 'Small Ticket'
  else:
    return 'Big Tiket'

caught_speeding(81,True)

caught_speeding(81,False)

