# -*- coding: utf-8 -*-
"""Lab3_19521970.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wzIcOwCqzFPlbbIijW3wnqyXT2t0hbaK
"""

import matplotlib.pyplot as plt

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

import numpy as np
x = np.linspace(0,5,11)
y = x ** 2

x

y

plt.plot(x,y,'r')
plt.xlabel('X Axis Title Here')
plt.ylabel('Y Axis Title Here')
plt.title('String Title Here')
plt.show()

plt.subplot(1,2,1)
plt.plot(x,y,'r--')
plt.subplot(1,2,2)
plt.plot(y,x,'g*-');

fig = plt.figure()
axes = fig.add_axes([0.1, 0.1, 0.8, 0.8])
axes.plot(x,y,'b')
axes.set_xlabel('Set X Label')
axes.set_ylabel('Set Y Label')
axes.set_title('Set Title')

fig = plt.figure()
axes1 = fig.add_axes([0.1, 0.1, 0.8, 0.8])
axes2 = fig.add_axes([0.2, 0.5, 0.4, 0.3])
axes1.plot(x,y,'b')
axes1.set_xlabel('X_Label_axes2')
axes2.set_ylabel('Y_Label_axes2')
axes1.set_title('Axes 2 Title')
axes2.plot(y,x,'r')
axes2.set_xlabel('X_Label_axes2')
axes2.set_ylabel('Y_Label_axes2')
axes2.set_title('Axes 2 Title')

fig,axes = plt.subplots()
axes.plot(x,y,'r')
axes.set_xlabel('x')
axes.set_ylabel('y')
axes.set_title('title');

fig, axes = plt.subplots(nrows = 1, ncols = 2)

axes

for ax in axes:
  ax.plot(x,y,'b')
  ax.set_xlabel('x')
  ax.set_ylabel('y')
  ax.set_title('title')
fig

fig,axes = plt.subplots(nrows = 1, ncols = 2)
for ax in axes:
  ax.plot(x,y,'g')
  ax.set_xlabel('x')
  ax.set_ylabel('y')
  ax.set_title('title')
fig
plt.tight_layout()

fig,axes = plt.subplots(figsize = (12,3))
axes.plot(x,y,'r')
axes.set_xlabel('x')
axes.set_ylabel('y')
axes.set_title('title');

fig.savefig("filename.png")

fig.savefig("filename.png", dpi = 200)

ax.set_title("title")

ax.set_xlabel("x")
ax.set_ylabel("y")

fig = plt.figure()
ax = fig.add_axes([0, 0, 1, 1])
ax.plot(x, x ** 2,label = "x ** 2")
ax.plot(x, x ** 3,label = "x ** 3")
ax.legend()

fig,axes = plt.subplots(1, 3, figsize = (12, 4))
axes[0].plot(x, x ** 2, x, x ** 3)
axes[0].set_title("default axes ranges")
axes[1].plot(x, x ** 2,x , x ** 3)
axes[1].axis('tight')
axes[1].set_title("tight axes")

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt 
import matplotlib.image as mpimg
import seaborn as sns
# %matplotlib inline
sns.get_dataset_names()

tips = sns.load_dataset("tips")
tips.head()

ax = sns.scatterplot(x = "total_bill", y = "tip", data = tips)

sns.relplot(x= "total_bill", y = "tip", data = tips, kind = "scatter",  hue = "sex", size = "size",)

sns.catplot(x ="sex", y = "total_bill", hue = "day", data = tips, kind = "strip")

sns.catplot(x = "sex", y="total_bill", hue = "day", data = tips, kind = "strip"
            ,jitter = False, dodge = True)

sns.catplot(x = "sex", y = "total_bill", hue = "day", data = tips , kind = "box")

from google.colab import files
 
uploaded = files.upload()

# Commented out IPython magic to ensure Python compatibility.
# III. Exercises
# 1. Job Market

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
# %matplotlib inline
data = pd.read_csv('job-market.csv')
data.dropna(inplace=True)
data

